---
title: "Pro-sepsis"
#author: "Nartlada Chantharojwong & Vorapathu Thaineua"
date: "Compiled on `r format(Sys.time(), '%B %d, %Y - %H:%M')`"
output:
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE
)

library(tidyverse)
library(haven)      # Read SAS dataset
library(purrr)      # Apply function (sum) to each element
library(scales)     # Format numeric values
library(labelled)   # Set organism variable labels
library(DiagrammeR) # Create flowchart
library(gtsummary)  # Create publication-ready summary tables
library(survival)   # Survival analysis
library(gt)         # Format gtsummary output

theme_gtsummary_compact(font_size = 10)
```

```{r functions}
# Format gtsummary outputs after merging
format_table <- function(t) {

  gt <- t %>%
    # Convert to gt and use default left align
    as_gt() %>%
    # Standard column width to fit every table
    cols_width(
      label ~ px(230),
      starts_with('p.value') ~ px(50),
      everything() ~ px(70)
    ) %>%
    tab_style(
      style = cell_text(weight = "bold"),
      locations = cells_row_groups()) %>%
    tab_style(
      style = cell_text(weight = "bold"),
      locations = cells_body(
        columns = label,
        rows = variable %in% c(
          "gramneg",
          "grampos",
          "gramneg_m",
          "grampos_m"
        )
      )
    ) %>%
    tab_options(
      # row_group.border.top.width = 1,
      # row_group.border.bottom.width = 1,
      table.border.bottom.style = "hidden"
    )

  return(gt)

}

notzero <- function(X)
{
  if (X > 0)
    return(TRUE)
  else
    return(FALSE)
}

# Sort dichotomous variables by descending frequency
sort_var <- function(df, ...) {
  df %>%
    filter(!is.na(dead28c)) %>%
    select(...) %>%
    map_dbl(sum, na.rm = TRUE) %>%
    sort(decreasing = TRUE) %>% 
    Filter(notzero,.)    
}

create_ttO <- function(df, vars, bold = TRUE, label = '') {
  t <- tbl_summary(df %>% select(vars), 
                   missing = "no") %>%
    modify_header(update = list(
      label ~ label,
      stat_0 ~ "**Overall**<br>N = {N}"
    )) %>%
    modify_footnote(update = stat_0 ~ NA)
  if (bold == TRUE) {
    t <- t %>% bold_labels() %>%
      add_stat_label()
  }
  return(t)
}

create_tt <- function(df,
                      vars,
                      bold = TRUE,
                      label = '') {
  t <- tbl_summary(df %>% select(vars),
                   by = dead28c,
                   missing = "no") %>%
    add_p(test.args = all_tests("fisher.test") ~ list(workspace = 2e9)) %>%
    # Bold p-value if significant
    bold_p(t = 0.05) %>%
    add_overall() %>% 
    modify_header(
      update = list(
        label ~ "",
        all_stat_cols(stat_0 = FALSE) ~ "**{level}**<br>N = {n}",
        stat_0 ~ "**Overall**<br>N = {N}"
      )
    ) %>%
    modify_spanning_header(c('stat_0', 'stat_1', 'stat_2', 'p.value') ~ "**Overall**, N = {N}") %>%
    modify_footnote(update = all_stat_cols() ~ NA)
  if (bold == TRUE) {
    t <- t %>% bold_labels() %>%
      add_stat_label()
  }
  return(t)
}

create_ts <- function(df, vars) {
  tbl_strata(
    df %>% select(sepsis, dead28c, vars),
    strata = sepsis,
    .tbl_fun =
      ~ .x %>%
      tbl_summary(by = dead28c,
                  missing = "no") %>%
      add_p(test.args = all_tests("fisher.test") ~ list(workspace = 2e9)) %>%
      # Bold p-value if significant
      bold_p(t = 0.05) %>%
      bold_labels() %>%
      add_stat_label() %>%
      modify_header(update = list(
        label ~ "",
        all_stat_cols() ~ "**{level}**<br>N = {n}"
      )) %>%
      modify_footnote(update = all_stat_cols() ~ NA),
    .header = "**{strata}**, N = {n}"
  )
}

create_ts2 <- function(df, vars) {
  tbl_strata(
    df %>% select(sepsis, dead28c, vars),
    strata = sepsis,
    .tbl_fun =
      ~ .x %>%
      tbl_summary(by = dead28c,
                  missing = "no") %>%
      add_p(test.args = all_tests("fisher.test") ~ list(workspace = 2e9)) %>%
      # Bold p-value if significant
      bold_p(t = 0.05) %>%
      modify_header(update = list(
        label ~ "",
        all_stat_cols() ~ "**{level}**<br>N = {n}"
      )) %>%
      modify_footnote(update = all_stat_cols() ~ NA),
    .header = "**{strata}**, N = {n}"
  )
}

create_t3 <- function(df, outcome = dead28c, vars) {
  outcome = enquo(outcome)
  df %>%
    select(!!outcome, vars) %>%
    tbl_summary(by = !!outcome) %>%
    add_p(test.args = all_tests("fisher.test") ~ list(workspace = 2e9)) %>%
    # Bold p-value if significant
    bold_p(t = 0.05) %>%
    modify_header(update = list(
      label ~ "",
      all_stat_cols() ~ "**{level}**<br>N = {n}")) %>%
    modify_footnote(update = all_stat_cols() ~ NA)
}
```

```{r data}
# Screening
df_scr <-
  read_sas(
    "C:/MyD/Sepsis_Pro/MF/tblPart1.sas7bdat",
    "C:/MyD/Sepsis_Pro/LABEL/prosepsis.sas7bcat"
    # "C:/Projects/ProSepsis/SAS/MF/tblPart1.sas7bdat",
    # "C:/Projects/ProSepsis/SAS/LABEL/prosepsis.sas7bcat"
  )

# Enrollment
df_enr <-
  read_sas(
    "C:/MyD/Sepsis_Pro/MF/psmast.sas7bdat",
    "C:/MyD/Sepsis_Pro/LABEL/prosepsis.sas7bcat"
    # "C:/Projects/ProSepsis/SAS/MF/psmast.sas7bdat",
    # "C:/Projects/ProSepsis/SAS/LABEL/prosepsis.sas7bcat"
  ) %>%
  mutate(
    dead28c = factor(
      dead28c,
      levels = c(1, 2),
      labels = c('Dead', 'Alive')
    ),
    sepsis = factor(
      Review_Sepsisr,
      levels = c(2,1),
      labels = c('Non-sepsis', 'Sepsis')
    ),
    presepsin_q51 = cut(presepsin_res1, breaks = c(0,594, 1055, 1594, 3273, Inf),
                        labels = c('≤ 594', '595-1055','1056-1594','1595-3273','≥ 3274')),
    procal_q51 = cut(Procal_res1, breaks = c(0, 0.285, 1.750, 7.150, 45.3, Inf),
                        labels = c('≤ 0.285', '0.286-1.750','1.751-7.150','7.151-45.3', '≥ 45.31')),
    # lactate_q51 = cut(lactate_res1,
    #                 breaks = quantile(lactate_res1,
    #                 probs = seq(0, 1, 0.2),
    #                     na.rm = TRUE),
    #   include.lowest = TRUE,
    #   labels = c('≤ 1.05', '1.06-1.75', '1.76-2.75','2.76-4.35','≥ 4.36')),
     lactate_q51 = cut(lactate_res1, breaks = c(0, 1.1, 1.8, 2.8, 4.4, Inf),
                        labels = c('≤ 1.10', '1.11 - 1.80','1.81 - 2.80','2.81 - 4.40', '≥ 4.41')),
    
    across(
      c(
        Sex,
        BMIgp_asia,
        PlaceChk_n,
        OPD_IPD,
        Sepsis_Scale,
        HIV,
        Covid21,
        DischargeStatus,
        DischargeType
      ),
      ~ as_factor(.)
    ),
    across(
      c(
        Refer,
        QSofa,
        UnSmoke:UnAlcohol,
        NP,
        CB,
        Sofa_Sepsis,
        vasopressor,
        oxygensupp,
        Hypoglycemia,
        HBsAgr,
        HBc,
        AntiHBs,
        AntiHCV,
        Influenza,
        Leptor,
        MalariaR,
        Melio,
        RSV
      ),
      ~ ifelse(. == 2, 0, .)
    ),
    covid19_r = ifelse(grepl('1', Covid_tests, fixed = TRUE), 1, 0),
    dengue_r  = ifelse(grepl('1', Dengue_tests, fixed = TRUE), 1, 0),
    denguel_r = ifelse(grepl('1', DengueL_tests, fixed = TRUE), 1, 0),
    hbshcv_r  = ifelse(grepl('1', HBSHCV_tests, fixed = TRUE), 1, 0),
    scrubt_r  = ifelse(grepl('1', ScrubT_tests, fixed = TRUE), 1, 0),
    TachypneaOrDyspnea = ifelse(CCTachypnea ==1 | CCDyspnea == 1,1,0),
    NauseaOrVomiting  = ifelse(CCNausea == 1 | CCVomiting == 1,1,0),
    TachypneaAndDyspnea = ifelse(CCTachypnea ==1 & CCDyspnea == 1,1,0),
    NauseaAndVomiting  = ifelse(CCNausea == 1 & CCVomiting == 1,1,0)
  )

var_label(df_enr) <- list(
  achromobacter      = paste0(var_label(df_enr$achromobacter),
                              ' (', sum(df_enr$achromobacter_i),    ifelse(sum(df_enr$achromobacter_i) == 1,' isolation)',' isolations)')),
  acinetobacter_b    = paste0(var_label(df_enr$acinetobacter_b),
                              ' (', sum(df_enr$acinetobacter_b_i),  ifelse(sum(df_enr$acinetobacter_b_i) == 1,' isolation)',' isolations)')),
  acinetobacter_l    = paste0(var_label(df_enr$acinetobacter_l),
                              ' (', sum(df_enr$acinetobacter_l_i),  ifelse(sum(df_enr$acinetobacter_l_i) == 1,' isolation)',' isolations)')),
  aerobic            = paste0(var_label(df_enr$aerobic),
                              ' (', sum(df_enr$aerobic_i),          ifelse(sum(df_enr$aerobic_i) == 1,' isolation)',' isolations)')),
  aeromonas          = paste0(var_label(df_enr$aeromonas),
                              ' (', sum(df_enr$aeromonas_i),        ifelse(sum(df_enr$aeromonas_i) == 1,' isolation)',' isolations)')),
  burkholderia_c     = paste0(var_label(df_enr$burkholderia_c),
                              ' (', sum(df_enr$burkholderia_c_i),   ifelse(sum(df_enr$burkholderia_c_i) == 1,' isolation)',' isolations)')),
  burkholderia_p     = paste0(var_label(df_enr$burkholderia_p),
                              ' (', sum(df_enr$burkholderia_p_i),   ifelse(sum(df_enr$burkholderia_p_i) == 1,' isolation)',' isolations)')),
  dermacoccus        = paste0(var_label(df_enr$dermacoccus),
                              ' (', sum(df_enr$dermacoccus_i),      ifelse(sum(df_enr$dermacoccus_i) == 1,' isolation)',' isolations)')),
  edwardsiella       = paste0(var_label(df_enr$edwardsiella),
                              ' (', sum(df_enr$edwardsiella_i),     ifelse(sum(df_enr$edwardsiella_i) == 1,' isolation)',' isolations)')),
  enterobacter       = paste0(var_label(df_enr$enterobacter),
                              ' (', sum(df_enr$enterobacter_i),     ifelse(sum(df_enr$enterobacter_i) == 1,' isolation)',' isolations)')),
  enterococcus       = paste0(var_label(df_enr$enterococcus),
                              ' (', sum(df_enr$enterococcus_i),     ifelse(sum(df_enr$enterococcus_i) == 1,' isolation)',' isolations)')),
  escherichia        = paste0(var_label(df_enr$escherichia),
                              ' (', sum(df_enr$escherichia_i),      ifelse(sum(df_enr$escherichia_i) == 1,' isolation)',' isolations)')),
  haemophilus        = paste0(var_label(df_enr$haemophilus),
                              ' (', sum(df_enr$haemophilus_i),      ifelse(sum(df_enr$haemophilus_i) == 1,' isolation)',' isolations)')),
  klebsiella         = paste0(var_label(df_enr$klebsiella),
                              ' (', sum(df_enr$klebsiella_i),       ifelse(sum(df_enr$klebsiella_i) == 1,' isolation)',' isolations)')),
  kluyvera           = paste0(var_label(df_enr$kluyvera),
                              ' (', sum(df_enr$kluyvera_i),         ifelse(sum(df_enr$kluyvera_i) == 1,' isolation)',' isolations)')),
  micrococcus        = paste0(var_label(df_enr$micrococcus),
                              ' (', sum(df_enr$micrococcus_i),      ifelse(sum(df_enr$micrococcus_i) == 1,' isolation)',' isolations)')),
  morexella          = paste0(var_label(df_enr$morexella),
                              ' (', sum(df_enr$morexella_i),        ifelse(sum(df_enr$morexella_i) == 1,' isolation)',' isolations)')),
  proteus            = paste0(var_label(df_enr$proteus),
                              ' (', sum(df_enr$proteus_i),          ifelse(sum(df_enr$proteus_i) == 1,' isolation)',' isolations)')),
  providencia        = paste0(var_label(df_enr$providencia),
                              ' (', sum(df_enr$providencia_i),      ifelse(sum(df_enr$providencia_i) == 1,' isolation)',' isolations)')),
  pseudohyphae       = paste0(var_label(df_enr$pseudohyphae),
                              ' (', sum(df_enr$pseudohyphae_i),     ifelse(sum(df_enr$pseudohyphae_i) == 1,' isolation)',' isolations)')),
  salmonella         = paste0(var_label(df_enr$salmonella),
                              ' (', sum(df_enr$salmonella_i),       ifelse(sum(df_enr$salmonella_i) == 1,' isolation)',' isolations)')),
  staphylococcus     = paste0(var_label(df_enr$staphylococcus),
                              ' (', sum(df_enr$staphylococcus_i),   ifelse(sum(df_enr$staphylococcus_i) == 1,' isolation)',' isolations)')),
  stenotrophomonas   = paste0(var_label(df_enr$stenotrophomonas),
                              ' (', sum(df_enr$stenotrophomonas_i), ifelse(sum(df_enr$stenotrophomonas_i) == 1,' isolation)',' isolations)')),
  streptococcus_vi   = paste0(var_label(df_enr$streptococcus_vi),
                              ' (', sum(df_enr$streptococcus_vi_i), ifelse(sum(df_enr$streptococcus_vi_i) == 1,' isolation)',' isolations)')),
  streptococcus_an   = paste0(var_label(df_enr$streptococcus_an),
                              ' (', sum(df_enr$streptococcus_an_i), ifelse(sum(df_enr$streptococcus_an_i) == 1,' isolation)',' isolations)')),
  streptococcus_bo   = paste0(var_label(df_enr$streptococcus_bo),
                              ' (', sum(df_enr$streptococcus_bo_i), ifelse(sum(df_enr$streptococcus_bo_i) == 1,' isolation)',' isolations)')),
  streptococcus_co   = paste0(var_label(df_enr$streptococcus_co),
                              ' (', sum(df_enr$streptococcus_co_i), ifelse(sum(df_enr$streptococcus_co_i) == 1,' isolation)',' isolations)')),
  streptococcus_a    = paste0(var_label(df_enr$streptococcus_a),
                              ' (', sum(df_enr$streptococcus_a_i),  ifelse(sum(df_enr$streptococcus_a_i) == 1,' isolation)',' isolations)')),
  streptococcus_b    = paste0(var_label(df_enr$streptococcus_b),
                              ' (', sum(df_enr$streptococcus_b_i),  ifelse(sum(df_enr$streptococcus_b_i) == 1,' isolation)',' isolations)')),
  streptococcus_pn   = paste0(var_label(df_enr$streptococcus_pn),
                              ' (', sum(df_enr$streptococcus_pn_i), ifelse(sum(df_enr$streptococcus_pn_i) == 1,' isolation)',' isolations)')),
  streptococcus_su   = paste0(var_label(df_enr$streptococcus_su),
                              ' (', sum(df_enr$streptococcus_su_i), ifelse(sum(df_enr$streptococcus_su_i) == 1,' isolation)',' isolations)')),
  vibrio             = paste0(var_label(df_enr$vibrio),
                              ' (', sum(df_enr$vibrio_i),           ifelse(sum(df_enr$vibrio_i) == 1,' isolation)',' isolations)')),
  gramneg            = paste0(var_label(df_enr$gramneg),
                              ' (', sum(df_enr$gramneg_i),          ifelse(sum(df_enr$gramneg_i) == 1,' isolation)',' isolations)')),
  grampos            = paste0(var_label(df_enr$grampos),
                              ' (', sum(df_enr$grampos_i),          ifelse(sum(df_enr$grampos_i) == 1,' isolation)',' isolations)')),
  achromobacter_m    = var_label(df_enr$achromobacter),
  acinetobacter_b_m  = var_label(df_enr$acinetobacter_b),
  acinetobacter_l_m  = var_label(df_enr$acinetobacter_l),
  aerobic_m          = var_label(df_enr$aerobic),
  aeromonas_m        = var_label(df_enr$aeromonas),
  burkholderia_c_m   = var_label(df_enr$burkholderia_c),
  burkholderia_p_m   = var_label(df_enr$burkholderia_p),
  dermacoccus_m      = var_label(df_enr$dermacoccus),
  edwardsiella_m     = var_label(df_enr$edwardsiella),
  enterobacter_m     = var_label(df_enr$enterobacter),
  enterococcus_m     = var_label(df_enr$enterococcus),
  escherichia_m      = var_label(df_enr$escherichia),
  haemophilus_m      = var_label(df_enr$haemophilus),
  klebsiella_m       = var_label(df_enr$klebsiella),
  kluyvera_m         = var_label(df_enr$kluyvera),
  micrococcus_m      = var_label(df_enr$micrococcus),
  morexella_m        = var_label(df_enr$morexella),
  proteus_m          = var_label(df_enr$proteus),
  providencia_m      = var_label(df_enr$providencia),
  pseudohyphae_m     = var_label(df_enr$pseudohyphae),
  salmonella_m       = var_label(df_enr$salmonella),
  staphylococcus_m   = var_label(df_enr$staphylococcus),
  stenotrophomonas_m = var_label(df_enr$stenotrophomonas),
  streptococcus_vi_m = var_label(df_enr$streptococcus_vi),
  streptococcus_an_m = var_label(df_enr$streptococcus_an),
  streptococcus_bo_m = var_label(df_enr$streptococcus_bo),
  streptococcus_co_m = var_label(df_enr$streptococcus_co),
  streptococcus_a_m  = var_label(df_enr$streptococcus_a),
  streptococcus_b_m  = var_label(df_enr$streptococcus_b),
  streptococcus_pn_m = var_label(df_enr$streptococcus_pn),
  streptococcus_su_m = var_label(df_enr$streptococcus_su),
  vibrio_m           = var_label(df_enr$vibrio),
  gramneg_m          = var_label(df_enr$gramneg),
  grampos_m          = var_label(df_enr$grampos)
)

df_ipd <- filter(df_enr,OPD_IPD == "1 -IPD")
n_ipd  <- nrow(df_ipd)

df_ipd_sep <- filter(df_ipd, Review_Sepsisr == 1) 
  
n_ipd_sep  <- nrow(df_ipd_sep)

```

<br>

\newpage

**Table 1_1**: Descriptive statistical analysis of the baseline demographic data and clinical characteristics of the IPD sepsis cases at Nakhon Phanom and Mae Sot hospitals during November 2021- July 8, 2022 (N=`r n_ipd_sep`)

```{r t1_1}
df <- df_ipd_sep %>%
  mutate(
    Age_gp4 = cut(
      Age_year,
      breaks = c(0, 14, 44, 64 , Inf),
      labels = c('<15', '15-44', '45-64', '>64')
    ),
    occupation = fct_infreq(
      case_when(
        Occupation == 1 ~ 'Student',
        Occupation == 4 ~ 'Laborer',
        Occupation %in% c(5, 7) ~ 'Farmer',
        TRUE ~ 'Other'
      )
    )
  ) %>% 
  select(
    sepsis,
    dead28c,
    Age_year,
    Age_gp4,
    Sex,
    BMIgp_asia,
    PlaceChk_n,
    occupation,
    Refer,
    QSofa,
    Sepsis_Scale,
    lactate_res1, 
    lactate_q51,
    presepsin_res1,
    presepsin_q51,
    Procal_res1,
    procal_q51,
    CCFever:CCSputum,
    TachypneaOrDyspnea,
    NauseaOrVomiting,
    
    CCAbPain:CCJointPain,
    CCOther,
    IFTropSep:IFNerve,
    IFOth
    
  ) %>%
  set_variable_labels(
    Age_year     = 'Age',
    Age_gp4      = 'Age group',
    BMIgp_asia        = 'BMI range',
    PlaceChk_n   = 'Admission ward',
    Refer        = 'Transferred',
    QSofa        = '(Any) qSOFA >= 2 scores',
    Sepsis_Scale = 'Sepsis determination (SOFA)',
    IFTropSep     = 'Tropical infection',
    IFRespiratory = 'Respiratory',
    IFBlood       = 'Blood',
    IFGas         = 'Gastrointestinal track',
    IFUrine       = 'Urinary',
    IFSkin        = 'Skin/Soft tissue/bone',
    IFNerve       = 'Central nervous system',
    IFOth         = 'Others',
    occupation    = 'Occupation',
    lactate_q51   = 'Lactate (quintiles)',
    presepsin_q51 = 'Presepsin (quintiles)',
    procal_q51    = 'Procalcitonin (quintiles)',
    TachypneaOrDyspnea = 'Tachypnear OR Dyspnea',
    NauseaOrVomiting = 'Nausea OR Vomiting',
    CCSputum      ='Phlegm '
  ) %>% 
  zap_labels()

vars <- names(select(df, dead28c, Age_year:procal_q51))
t1t <- create_tt(df, vars)


vars <- append(names(sort_var(df, CCFever:CCJointPain)), c('dead28c', 'CCOther'))
t1t_cc <- create_tt(df, vars, FALSE)


vars <- append(names(sort_var(df, IFTropSep:IFNerve)), c('dead28c','IFOth'))
t1t_if <- create_tt(df, vars, FALSE)


t1 <- tbl_stack(list(t1t, t1t_cc, t1t_if),
                group_header = c('', 'Chief Complaint, n (%)', 'Source of Infection, n (%)')) %>%
  format_table() %>%
  tab_style(style = cell_borders(sides = "bottom", style = "hidden"),
            locations = cells_row_groups(groups = 1))
t1
```



